services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: ddb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    restart: unless-stopped